### ISSUE TITLE
Anchor Linking + GSAP ScrollTrigger

### ISSUE THREAD

**Issue by bryanberger** [ashthornton/asscroll#14]
Hi I just started using this library for a project, really great work by the way -- TY

I ran into a slight issue I wanted to document here with my workaround for now.

When using ScrollTrigger, specifically the `pin` option, ScrollTrigger wraps DOM elements with a `div.pin-spacer` ASScroll doesn't scrollTo the right container that are children of the pin spacers.

I had to do something like this to work around it for my navigation:
```
document.querySelector('nav').addEventListener('click', (event) => {
  if (event.target instanceof HTMLAnchorElement) {
    event.preventDefault()
    event.stopImmediatePropagation()

    const section = document.querySelector(event.target.hash)
    const parent = section.parentElement
    const isInPinSpacer = parent.classList.contains('pin-spacer')
    const offsetY = isInPinSpacer ? parent.offsetTop : section.offsetTop // <---- specifically here

    smoothScroll.scrollTo(offsetY)
  }
})
```

I would love any additional suggestions/thoughts. Thank you!

**Comment by ashthornton** [comment]
Hi @bryanberger thanks for giving this library a shot!

That's an interesting one which sounds quite specific to using it in combination with ScrollTrigger, but I will take a look and make sure ASScroll isn't getting in the way and get back to you.

Out of interest, are you using v1.6.1? I actually added some potential fixes specifically for anchor links in that version.

**Comment by bryanberger** [comment]
@ashthornton Yep, v1.6.1 -- I noticed the anchor changes, was eager to try it out which led me to the work around. Thanks for looking into it!

**Comment by ashthornton** [comment]
@bryanberger I've just made some improvements to the anchor link and tab focus functionality. Could you try the latest version (1.6.2) and let me know if that improves things for you? Otherwise could you make a reduced example of your on Codepen or similar and I can take a further look 👍
