### ISSUE TITLE
Tab Focus

### ISSUE THREAD

**Issue by paullangton** [ashthornton/asscroll#16]
First of all great work!

I noted that tab focus had been implemented so was excited to try on a new project. The tab focus seems to jump up and down between a and button tag elements.

I have updated your recent pen with on codepen with some additional links at the bottom so you can see what I mean when you tab.
https://codepen.io/plankton/pen/BaKmvyX

I changed the cdn to 1.6.1.

**Comment by ashthornton** [comment]
Thanks for letting me know @paullangton! I'll take a look and get back to you 👍

**Comment by ashthornton** [comment]
@paullangton please try the latest version (1.6.2) and let me know if it's working correctly now. I've tested with your Codepen and it works for me.

**Comment by paullangton** [comment]
Kudos to you Ash! both pen and project working as expected.

Thank you for such a quick fix and for sharing your work!

**Comment by ashthornton** [comment]
No worries @paullangton glad to hear it's working. If you'd like to share your project when it's done I could add it to the list of examples in the readme, I'm interested to see how it's been used!
