### ISSUE TITLE
Custom scrollbar not working properly

### ISSUE THREAD

**Issue by S-n-d** [ashthornton/asscroll#19]
First of all great work Ash, and thank you for sharing it! Giving this a shot in a new project.

I'm encountering the following problem: my .asscrollbar__handle is being set the same height of the viewport and isn't translating on scroll. It does show on scroll and hides on stop.

I'm not quite sure what I might be doing wrong but I've been looking at the codepen demo and my HTML structure is about the same: my `<main>` is the .asscroll-container and the .asscrollbar is its sibling. Only difference is that there's a `<nav>` element outside the .asscroll-container but if I remove it the problem remains. 

Any thoughts would be appreciated!

**Comment by S-n-d** [comment]
It looks like the issue only occurs when the total page length is less than ~200vh.

**Comment by ashthornton** [comment]
Thanks for pointing this out @S-n-d , this should now be fixed in the latest version (v.1.6.5)

**Comment by S-n-d** [comment]
Great work Ash! Thanks!
