### ISSUE TITLE
How would you implement scrolling to a section when using this library with gsap ?

### ISSUE THREAD

**Issue by clearly-outsane** [ashthornton/asscroll#20]
I love the integration of this library with scroll trigger so far but I've been unable to get gsap scrollTo working with this library. How should I go about implementing scrolling to anchor tags/sections

**Comment by ashthornton** [comment]
@clearly-outsane Scrolling to anchor tags should work without the need for GSAP's scrollTo plugin. Have you tried the latest version of ASScroll?

**Comment by clearly-outsane** [comment]
Ah yea nvm - I got it to work with ASScroll.scrollTo - one problem I have now is the scroll is too fast - is there any way to increase the duration of the animation ?

**Comment by ashthornton** [comment]
@clearly-outsane you could always tween a value and call `ASScroll.scrollTo(val)` when it updates, something like this:

```
const scroll = { value: 0 }

function scrollToSection() {
    scroll.value = -ASScroll.smoothScrollPos
    gsap.to(scroll, {
        value: targetPosition, // targetPosition being the pixel position of where to scroll to
        onUpdate: () => {
            ASScroll.scrollTo(scroll.value)
        }
    })
}
```

**Comment by clearly-outsane** [comment]
Ohh I wasn't aware you could use it like that thank you very much :) You've been of great help

**Comment by ashthornton** [comment]
You're welcome :)
