### ISSUE TITLE
jump immediately to Y-position without scroll animation

### ISSUE THREAD

**Issue by richard-unterberg** [ashthornton/asscroll#22]
Thanks Ash for this great piece of code,

The following is more a feature request than an "issue"
I´m experimenting a lot with this bundled with GSAP´s scrolltrigger. In my lastest application, it opens a fullscreen (scrollable) overlay. on close it should instantly jump to the last position (It remembers the offset value in a variable and apply it via `"scrollTo(someoffset)"`). I´m wondering if it´s possible to jump immediately to a Y position without animating the scroll to there (example below). This could open up the possibilities for some nice transitions.

example of jumping content:
![example](https://user-images.githubusercontent.com/34207253/97307002-6d524500-185f-11eb-824a-8346534870d8.gif)

Looking forward to read from you :)

Thanks and Greetings,
Richard

**Comment by ashthornton** [comment]
Hi @richard-unterberg , without seeing your full setup I think the best way to do what you're asking is to explicitly set the target scroll positions as well as the current smoothed scroll position like so:

```
ASScroll.Scroll.scrollPos = y
ASScroll.Scroll.smoothScrollPos = y
```

`y` would need to be the negative value of the position you want to scroll to

I think I will add a method to do this without manually changing values in the future since I've needed to do this before as well.

**Comment by richard-unterberg** [comment]
absolutely awesome. works for me <3

**Comment by MatHackDev** [comment]
Hi @ashthornton , thanks for this libs ! 

I'm using nuxt and my usecase it's transition between two pages.

I would like to go to the top of my page without smooth, but this code it's obseleted 
`ASScroll.Scroll.scrollPos = y
ASScroll.Scroll.smoothScrollPos = y`

Do you have a method or code ?

**Comment by ashthornton** [comment]
Hi @MatHackDev, if you're using v2 you should be able to just set `ASScroll.currentPos = 200` for example, as outlined in the docs [here](https://github.com/ashthornton/asscroll#asscrollcurrentpos--number). Does this not work for you?

**Comment by MatHackDev** [comment]
Thanks for the quick answer :)

I had to change my way of doing things in my transition beceause currentPos apply after enable()

But it's works now ! Thanks.
