### ISSUE TITLE
URL with hash not scrolling to proper section on page load

### ISSUE THREAD

**Issue by jbarkun** [ashthornton/asscroll#25]
Hi again! I'm pretty sure the issue here is between the chair and the keyboard, but I've been banging my head against the wall for a couple of hours and would appreciate being pointed in the right direction.

I'm having trouble when clicking on links to other pages that have a hash in the URL. Ideally I would want the user to be brought down to the corresponding ID on the destination page, but that isn't happening. It's hard to create a codepen to demonstrate since it relies on the URL, but my setup is identical to [GSAP's ASScroll integration demo](https://codepen.io/ashthornton/pen/PoZRwPW).

I've also tried grabbing the URL hash after ASScroll has been enabled and manually scrolling down to that location:

```javascript
var hash = window.location.hash.substr(1);
if ( hash.length ) {
	var hash_target = $('#' + hash);
	if (hash_target.length) {
		gsap.to(window, {
			duration: 0.6,
			scrollTo: {y: $(hash_target), offsetY: scrollOffset}
		});
	}
}
```

But immediately after the window scrolls to the proper location, it stubbornly scrolls right back up to the top of the page.

Any ideas on how I can resolve this?

Thanks again!

**Comment by ashthornton** [comment]
Hi @jbarkun, I haven't tested this but you may just need to update ASScroll's internal scroll positions as the GSAP tween progresses like:

```Javascript
gsap.to(window, {
	duration: 0.6,
	scrollTo: {y: $(hash_target), offsetY: scrollOffset},
	onUpdate: () => {
		ASScroll.Scroll.scrollPos = y
		ASScroll.Scroll.smoothScrollPos = y
	}
});
```

But it's likely that animating the native window position like that will conflict with ASScroll. If you want to animate the scroll position you are better off doing something like this:

```Javascript
const scroll = { value: 0 }

function scrollToSection() {
    scroll.value = -ASScroll.smoothScrollPos

    gsap.to(scroll, {
        value: targetPosition, // targetPosition being the pixel position of where to scroll to
        duration: 1,
        ease: 'expo.out',
        onUpdate: () => {
            ASScroll.scrollTo(scroll.value)
        }
    })
}
```

If you want to snap to the scroll position like the native browser behaviour for anchor links you can just set the internal scroll positions like so:

```Javascript
ASScroll.Scroll.scrollPos = y
ASScroll.Scroll.smoothScrollPos = y
```

Let me know how you get on.

**Comment by jbarkun** [comment]
Thanks for your help! I ended up taking your final suggestion, since animating the scroll seemed to be a little wonky on some page loads.

Here's the final code for anyone who has the same issue:
```javascript
var hash = window.location.hash.substr(1);
if ( hash.length ) {
	var hash_target = $('#' + hash);
	if (hash_target.length) {
		var init_scroll_pos = $(hash_target).offset().top;
		asscroll.Scroll.scrollPos = -init_scroll_pos;
		asscroll.Scroll.smoothScrollPos = -init_scroll_pos;
	}
}
```

**Comment by ashthornton** [comment]
No worries @jbarkun! You're the second person that has needed this so I think I'll add a method to snap to a scroll position rather than lerp to it like what `.scrollTo()` does.
