### ISSUE TITLE
Doesn't work on mobile starting from version 1.7.0

### ISSUE THREAD

**Issue by kekkorider** [ashthornton/asscroll#26]
Hey Ash, I was testing a new project I'm working on that uses version `1.7.3` and saw that 🍑scroll is not initialized on mobile.

On another project I still have version `1.5.9` and it works perfectly, so I took some time to investigate and found out that problems start arise with version `1.7.0`.

On `1.7.0`, smoothscroll is really "janky";  it seems every calculations screw up and the progress reaches 100% way before the end of the page.

On `1.7.1` it simply doesn't work. The styles on `.asscroll-container` are not even applied.

Versions `1.7.2` and `1.7.3` have the same issue.

Here is how I initialize 🍑scroll:
```js
new ASScroll(
  disableRaf: true,
  scrollbarStyles: false
})
```
As you can see, no fancy weird wizardry of whatsoever.

This happens on both my dev environment (Chrome 87 with device emulation on an early 2015 MBP with Catalina) and my phone (Huawey Mate 10 Lite with Chrome 87 and Android 8.0.0).

Unfortunately, I can't share any video or link because this project is under NDA, hope you can reproduce the bug easily.

**Comment by ashthornton** [comment]
Hey Francesco!

Can I confirm two things:
1. are you using the latest version: 1.7.3
2. is the smooth scroll being 'janky' just affecting mobile, or desktop as well?

**Comment by kekkorider** [comment]
> 1. are you using the latest version: 1.7.3
> 2. is the smooth scroll being 'janky' just affecting mobile, or desktop as well?

1. Yes, I was using version `1.7.3`, and then I rolled back to version `1.5.9` upgrading it one version at a time. Until version `1.6.5` everything goes perfectly
2. Yes, only on mobile. It works like a charm on desktop

**Comment by ashthornton** [comment]
Ok so some changes were made in 1.7.1 in favour of improving mobile scroll performance and by default doesn't translate the page element. If you want to bring back the way it was before you can set `disableOnTouch: false` in the options.

If you're going to be doing any DOM + WebGL syncing I would recommend leaving that as true and taking a look at this for a mobile setup: https://codepen.io/ashthornton/pen/f0db400416fff43ad5096b45f6974de4

It's something I put together very quickly yesterday to demonstrate native mobile scrolling with no WebGL lag. The important thing in this setup seems to be using that `.pointer-blocker` element. But if your canvas is over your DOM it should be fine as long as its got `pointer-events: none` on it.

You can visit this link on your mobile: https://codepen.io/ashthornton/full/f0db400416fff43ad5096b45f6974de4
to see it without CodePen UI around it. Would be interesting to see if you have any issues with that.

Let me know any issues.
