### ISSUE TITLE
Adjust scroll speed

### ISSUE THREAD

**Issue by will-r-chase** [ashthornton/asscroll#27]
Just started using this library on a new project and I'm really loving it. 

As a feature request I would love if I could adjust the scroll speed. Something like `asscroll.setSpeed(0.5)` 

Thanks for all the work on this!

**Comment by ashthornton** [comment]
Hey @will-r-chase, I suspect the option you're looking for is `ease`. The lower this number in the ASScroll options, the slower the scroll speed will be. Let me know if this wasn't what you're looking for.

**Comment by will-r-chase** [comment]
Hi Ash, thanks, indeed setting ease handles most of it. The only thing I haven't been able to figure out is dynamically changing the ease. This is probably me just being dumb, but I couldn't find a simple way to change the ease once I scrolled into a particular section for example, without remaking the scroll object, which didn't seem like a good idea.

**Comment by ashthornton** [comment]
Ah I see, if you'd like to change the easing after initialisation you can access that property via `ASScroll.Scroll.ease` which will allow you to change it on the fly.
