### ISSUE TITLE
Uncaught SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by Mishkamshka** [ashthornton/asscroll#30]
Hi, I'm using ASSCROLL for the first time, and I'm stuck. I've tried to figure it out by myself, but I'm not very knowledgeable in JS.

I copied the GSAP x Asscroll Codepen Js and my site now says "Uncaught SyntaxError: Cannot use import statement outside a module". I literally copied and pasted it. 
I add the JS file to my Js folder, and I added it to header.php and functions.php, but I can't get it to work. What am I doing wrong? 
Thank you

**Comment by ashthornton** [comment]
Hi @Mishkamshka, that codepen demo is used with an ES module environment hence the `import` statements. If you want to use it using regular `<script>` tags you can use the compiled version via JSDelivr:

`<script src="https://cdn.jsdelivr.net/npm/@ashthornton/asscroll@1.7.4/build/asscroll.min.js"></script>`

Then initialise in your JS like:

`const asscroll = new ASScroll.default()`
