### ISSUE TITLE
Question about data prop usage in HTML

### ISSUE THREAD

**Issue by stevengrimaldo** [ashthornton/asscroll#32]
Is there a plan to put in the README the available properties in HTML? or is there and i'm not seeing it?

I ask because i am comparing using this to locomotive and i see you have data-speed available which i like but it makes me then want to know what else i can do with ASS.

thank you :)

**Comment by ashthornton** [comment]
Hi @stevengrimaldo , where are you seeing the `data-speed` attribute?

ASScroll only provides smooth scroll, which you then combine with your own way of animating things on scroll like by using [GSAP's ScrollTrigger](https://greensock.com/docs/v3/Plugins/ScrollTrigger) as shown in [this demo](https://codepen.io/ashthornton/pen/PoZRwPW).
