### ISSUE TITLE
Middle Click Scrolling

### ISSUE THREAD

**Issue by Namchee** [ashthornton/asscroll#33]
Great library you have here!

I want to request a feature: support for middle-click scrolling.
As far as I know, this library doesn't middle-click scrolling which obviously hinders Accessibility.

**Comment by ashthornton** [comment]
Hi @Namchee , middle click scrolling should work fine. At least it does on my Windows machine. How are you testing?

**Comment by Namchee** [comment]
Tested it locally (zero-config) with:

- **OS**: Ubuntu 20.04
- **NPM Version**: 6.14.11
- **Browser**: Version 86.0.4240.198 (Official Build) (64-bit)

I've also tried the CodePen version you provided as a demo. Both didn't work

**Comment by ashthornton** [comment]
@Namchee I've set up a virtual machine running Ubuntu 20.04 and middle-click scrolling works fine in Firefox. I've looked into middle-click scrolling Chrome and it seems you need to either install [this extension](https://chrome.google.com/webstore/detail/autoscroll/occjjkgifpmdgodlplnacmkejpdionan), or modify some hardware settings via `xinput`.

Can you confirm your setup so I can try to re-produce more accurately?

**Comment by Namchee** [comment]
@ashthornton I've tried the demo on Firefox on Ubuntu 20.04, it works normally seems I forgot to set the `auto-scroll` options there.

As for Chrome, still no luck, even with the extension. I think I'll play around with `xinput`. I'll give you updates about that as soon as possible.

**Comment by Namchee** [comment]
Tried it on a Chrome in a VM, still doesn't work. Fortunately, running [this script](https://unix.stackexchange.com/questions/472398/can-i-make-middle-mouse-scrolling-on-linux-behave-more-like-autoscrolling-on-win/472451#472451) on that VM fixes the middle-click scrolling issues.

I think I can safely close this issue, as this is not related to the library at all (you can remove the `bug` label too!). Thank you for your time.
