### ISSUE TITLE
How to use with libs like AOS (animate on scroll)?

### ISSUE THREAD

**Issue by urbgimtam** [ashthornton/asscroll#37]
Hi.

When using with other libraries that use intersectionObserver like AOS, scrolling is smooth but the other library only executes/affects its target elements after smooth scroll stops. 

This leaves a huge blank area that looks an error, until the user stops scrolling, which then updates all effects.

Any ideas on what can be done?
I know that in GSAP we can use ScrollProxy, but AOS doesn't have anything like that.

**Comment by ashthornton** [comment]
Hi @urbgimtam, if that library relies solely on IntersectionObserver to detect when elements are in view, then unfortunately it won't be compatible with the smooth scroll technique that transforms the page, which is used by ASScroll and most other popular libraries.

This would be something I would ask the author of AOS about to see if there is a workaround.

**Comment by urbgimtam** [comment]
Ok, thank you
