### ISSUE TITLE
containerElement question

### ISSUE THREAD

**Issue by esseifforte** [ashthornton/asscroll#53]
Hi,
in [parameters.containerElement]  default is "[asscroll-container]", but if I wanted to apply for example "[my-container]",
and in html `<div my-container>`
the result is `<div my-container asscroll-container style=...........etc>`
why?
This is only a question for full customization.
Thanks in advance

**Comment by ashthornton** [comment]
Hi @esseifforte, ASScroll will add the `asscroll-container` and `asscroll` attributes to the relevant elements in order to apply some CSS in certain configurations. I may look at improving this by only adding these when the configuration is actually being used.
