### ISSUE TITLE
IE11 v2 Issue

### ISSUE THREAD

**Issue by Scaalees** [ashthornton/asscroll#54]
Hey,

I know you've dropped IE11 support for v2. All for it!
But I was wondering if there is anything we can do to get the plugin to resolve as it's throwing out a "syntax error".

If not, no probs, is there a working example of the ASScroll v1 working with gsap and scroll triggers?

Thanks,
Jake

**Comment by ashthornton** [comment]
Hi @Scaalees, I'm not sure what bundler you're using (if at all) but it's possible with Webpack for example, to include specific node modules for Babel to parse. This would convert the ASScroll source code into IE11 compatible code. I have done this in the past but I can't remember the correct config but a quick Google brings up different ways of doing it.

In terms of an ASScroll v1 + GSAP ScrollTrigger example, I've re-created the demo here: https://codepen.io/ashthornton/pen/8ebe087506b1c3c3199ae8a266259c2d

Let me know if this helps.

**Comment by Scaalees** [comment]
Hi @ashthornton, Thanks for getting back to me!

Yeah using webpack to bundle everything together. But was having a little trouble getting finding out what polyfill was needed.

Thanks for suppling with a ASScroll v1 demo, I'll look at implementing that rather than v2 for now.

Thanks again for your help!
Jake
