### ISSUE TITLE
Issues when using together with Next.js

### ISSUE THREAD

**Issue by LotharVM** [ashthornton/asscroll#58]
After trying several ways of using asscroll v2, I still haven't found a way to successfully use it in Next.js. In versions prior to v2, this worked:

```javascript
// _app.js

useEffect(() => {
  const ASScroll = require("@ashthornton/asscroll").default;
  const sc = new ASScroll();
  sc.enable();

  const handleRouteChange = () => {
    setTimeout(() => {
      sc.onResize(window.innerWidth, window.innerHeight);
    }, 500);
  };

  router.events.on("routeChangeComplete", handleRouteChange);
}, []);
```
(The  onResize was needed to calculate the new page height)

After upgrading to v2, though, I keep getting the `TypeError: ASScroll is not a constructor` error. I also tried to import it at the top (native and via next/dynamic), but then Webpack throws a `ReferenceError: self is not defined` error.

Any help is appreciated!

Thanks in advance :)

**Comment by ashthornton** [comment]
Hi @LotharVM, v2 fixed having to import or access the library with `.default`. You should just need to import via `require("@ashthornton/asscroll")`. Let me know if that fixes your issue.

**Comment by LotharVM** [comment]
@ashthornton if I remove the .default, it's returning `TypeError: Cannot read property 'setAttribute' of null`

**Comment by ashthornton** [comment]
@LotharVM I've seen that issue when there is no `[asscroll-container]` element on the page, or if you've updated that option then it will need to match what you've passed through.

The default HTML is:
```html
<body>
    <div asscroll-container>
        <div><!-- The Y translation will be applied to this element --></div>
    </div>
</body>
```

Do you have the container element on your page?

**Comment by LotharVM** [comment]
@ashthornton it works now! I was still using the old parameter names, that's why it couldn't find the container element. Thanks!

**Comment by LotharVM** [comment]
One other question though: Do you think that my approach in useEffect, so updating the page height after the `routeChangeComplete` event is the correct way of doing it? I couldn't get it to work any other way

**Comment by darkristy** [comment]
By any chance how are you wrapping the container in ._app.js because I keep getting this error "_null is not an object (evaluating 'this.containerElement.setAttribute')_"

**Comment by ashthornton** [comment]
> One other question though: Do you think that my approach in useEffect, so updating the page height after the `routeChangeComplete` event is the correct way of doing it? I couldn't get it to work any other way

I'm not familiar with Next.js but the concept would follow this timeline normally:
1. Navigate away
2. Disable ASScroll (`asscroll.disable()`)
3. Load next page + assets (images/videos etc.)
4. Enable ASScroll (`asscroll.enable({ newScrollElements: newPageElement }`)

This is if the actual page element that was scrolling had changed on navigation, which may not be the case for you. In which case then yes, calling `asscroll.resize()` after your page has updated and assets have loaded is a good approach.

**Comment by tienuur** [comment]
> @ashthornton it works now! I was still using the old parameter names, that's why it couldn't find the container element. Thanks!

Hi LotharVM, would you mind sharing a demo? I tried to work with asscroll in Nextjs as well. I cannot make it work...
I tried your method, and made sure I `require` the package without default. There is a `[asscroll-container]` attribute in the JSX as well. But it keeps giving me `TypeError: Cannot read property 'setAttribute' of null`.

`function MyApp({ Component, pageProps }) {
  const router = useRouter();

  useEffect(() => {
    const ASScroll = require("@ashthornton/asscroll");
    const asc = new ASScroll();
    asc.enable();
  }, []);

  return (
    <>
      <div asscroll-container>
        <div>
          <Component {...pageProps} />
        </div>
      </div>
    </>
  );
}

export default MyApp;`

Thank you in advance!

**Comment by tienuur** [comment]
> > @ashthornton it works now! I was still using the old parameter names, that's why it couldn't find the container element. Thanks!
> 
> Hi LotharVM, would you mind sharing a demo? I tried to work with asscroll in Nextjs as well. I cannot make it work...
> I tried your method, and made sure I `require` the package without default. There is a `[asscroll-container]` attribute in the JSX as well. But it keeps giving me `TypeError: Cannot read property 'setAttribute' of null`.
> 
> ```
> //_app.js
> 
> function MyApp({ Component, pageProps }) {
> 
>   useEffect(() => {
>     const ASScroll = require("@ashthornton/asscroll");
>     const asc = new ASScroll();
>     asc.enable();
>   }, []);
> 
>   return (
>     <>
>       <div asscroll-container>
>         <div>
>           <Component {...pageProps} />
>         </div>
>       </div>
>     </>
>   );
> }
> 
> export default MyApp;
> ```
> 
> Thank you in advance!

I found a solution: I have to explicitly state `asscroll-container="true"` to make it work.

**Comment by ashthornton** [comment]
Hi @tienuur , this must be a quirk with Nextjs and custom attributes. Glad you found a solution!

**Comment by tienuur** [comment]
@ashthornton Thanks! What a relief!

**Comment by darkristy** [comment]
Say you have paginated list, how do you resize the page when the list container height changes

**Comment by ashthornton** [comment]
`asscroll.resize()`

**Comment by darkristy** [comment]
Thanks man, i figure it out. I have to say this library has saved me alot headache.
