### ISSUE TITLE
Native scrollbar shows when I resize

### ISSUE THREAD

**Issue by hirnreich** [ashthornton/asscroll#60]
Hello,

I really like Asscroll but there is an issue with resizing:

Having scrolled down about 75%, if I resize the window, _the native scroll bar appears_ and doesn't go away. Asscroll still works though (but it looks kinda ugly).

I already removed some of my content and also tried adding more content - it still happens at about 75%+ ... very weird.

Btw, I already use my own resizing function, as it was even worse with the included one!

I hope you can help me ...

Cheers,

Nico

EDIT: I just found a solution but I guess it _should_ work without it. I set the overflow of the scroll container to 'hidden' manually in my CSS file.

**Comment by ashthornton** [comment]
Hi @hirnreich, could you provide me with a working demo of this issue? It sounds like you may have some other CSS/JS affecting the container, as this isn't an issue when only ASScroll is running.
