### ISSUE TITLE
Add a jumpTo type method

### ISSUE THREAD

**Issue by jakewhiteley** [ashthornton/asscroll#71]
Sometimes you want to get the smoothed element to a Y offset without lerping there.

Could we get a `jumpTo()` method, or a flag on `scrollTo` which indicates the new position should be set instantly, rather than lerped to?

**Comment by ashthornton** [comment]
@jakewhiteley did you try just setting `asscroll.currentPos = y`? As per the example here: https://github.com/ashthornton/asscroll#asscrollcurrentpos--number
