### ISSUE TITLE
Does not scroll while mouse is over iframe.

### ISSUE THREAD

**Issue by iamlinkus** [ashthornton/asscroll#81]
I've added a video embed iframe on my page and noticed that I'm unable to scroll while the mouse is hovering over the iframe. The readme states that it shouldn't stop working in such a situation, but it does.

Steps to reproduce:
1. Create a page that uses asscroll and has an iframe.
2. Open that page, scroll to the iframe, wait till the scroll ease stops completely.
3. Try to scroll again while hovering over the iframe. No scroll happens (the iframe hijacks the scroll event).

**Comment by ashthornton** [comment]
Hey @iamlinkus, this example has an iframe and it seems to be working as intended for me: https://codepen.io/ashthornton/pen/YzWXZqL

It will still try to continue to scroll within the iframe for a certain amount of time until you stop scrolling, then it will continue scrolling outside of the iframe.

Does that example work for you? What browser, OS and type of mouse are you using?

**Comment by iamlinkus** [comment]
Opened your link on MacOS chrome, tried to scroll and it had the same bug/behavior that my website had. Then started thinking that if you're saying that it behaves as it should, there's something different on your side. Then I opened safari and it works as it should there, I can continue to scroll.

So this seems like a bug only on MacOS Chrome (both latest versions). Tried both the trackpad and a scroll-wheeled mouse.

**Comment by iamlinkus** [comment]
I have no idea what happened, but it suddenly started working, both on your example and on mine. It's super strange, since I didn't update anything. Nothing comes to mind, but it must've been something specifically broken with my browser which fixed itself after a browser restart. Sorry to have wasted your time on this, I'll close this issue now. Thanks for your help, as always!
